export const VITE_STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
export const VITE_STELLAR_RPC_URL="https://soroban-testnet.stellar.org"
export const VITE_STELLAR_CONTRACT_ID="CC6VP5I7AZWCL3HXPONFRYSZBHJCNPJHOSD463TQPGX5DKIWXVHJIJYB"
