// @ts-nocheck — auto-generated by Soroban CLI, do not edit manually
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CC6VP5I7AZWCL3HXPONFRYSZBHJCNPJHOSD463TQPGX5DKIWXVHJIJYB",
  }
} as const


export interface GuestMessage {
  author: string;
  id: u64;
  likes: u64;
  message: string;
}

export interface Client {
  /**
   * Construct and simulate a add_message transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  add_message: ({author, message}: {author: string, message: string}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a get_messages transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_messages: (options?: MethodOptions) => Promise<AssembledTransaction<Array<GuestMessage>>>

  /**
   * Construct and simulate a like_message transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  like_message: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a message_count transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  message_count: (options?: MethodOptions) => Promise<AssembledTransaction<u32>>

  /**
   * Construct and simulate a delete_message transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  delete_message: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<string>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAQAAAAAAAAAAAAAADEd1ZXN0TWVzc2FnZQAAAAQAAAAAAAAABmF1dGhvcgAAAAAAEAAAAAAAAAACaWQAAAAAAAYAAAAAAAAABWxpa2VzAAAAAAAABgAAAAAAAAAHbWVzc2FnZQAAAAAQ",
        "AAAAAAAAAAAAAAALYWRkX21lc3NhZ2UAAAAAAgAAAAAAAAAGYXV0aG9yAAAAAAAQAAAAAAAAAAdtZXNzYWdlAAAAABAAAAABAAAAEA==",
        "AAAAAAAAAAAAAAAMZ2V0X21lc3NhZ2VzAAAAAAAAAAEAAAPqAAAH0AAAAAxHdWVzdE1lc3NhZ2U=",
        "AAAAAAAAAAAAAAAMbGlrZV9tZXNzYWdlAAAAAQAAAAAAAAACaWQAAAAAAAYAAAABAAAAEA==",
        "AAAAAAAAAAAAAAANbWVzc2FnZV9jb3VudAAAAAAAAAAAAAABAAAABA==",
        "AAAAAAAAAAAAAAAOZGVsZXRlX21lc3NhZ2UAAAAAAAEAAAAAAAAAAmlkAAAAAAAGAAAAAQAAABA=" ]),
      options
    )
  }
  public readonly fromJSON = {
    add_message: this.txFromJSON<string>,
        get_messages: this.txFromJSON<Array<GuestMessage>>,
        like_message: this.txFromJSON<string>,
        message_count: this.txFromJSON<u32>,
        delete_message: this.txFromJSON<string>
  }
}